package io.tanjundang.study.knowledge.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import io.tanjundang.study.test.IDCard;
import io.tanjundang.study.test.Person;

import io.tanjundang.study.knowledge.greendao.IDCardDao;
import io.tanjundang.study.knowledge.greendao.PersonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig iDCardDaoConfig;
    private final DaoConfig personDaoConfig;

    private final IDCardDao iDCardDao;
    private final PersonDao personDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        iDCardDaoConfig = daoConfigMap.get(IDCardDao.class).clone();
        iDCardDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        iDCardDao = new IDCardDao(iDCardDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);

        registerDao(IDCard.class, iDCardDao);
        registerDao(Person.class, personDao);
    }
    
    public void clear() {
        iDCardDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
    }

    public IDCardDao getIDCardDao() {
        return iDCardDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

}
